spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config_shared

  profiles:
    active: native

  security:
    user:
      name: revollet_master_config
      password: c1tyn0w@r3v0ll3t

server:
  port: 8081

